# privileged-constraint-template.yaml
apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8sdenyprivileged
spec:
  crd:
    spec:
      names:
        kind: K8sDenyPrivileged
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8sdenyprivileged
        
        violation[{"msg": msg, "details": {}}] {
            container := input.review.object.spec.containers[_]
            container.securityContext.privileged
            msg := sprintf("Privileged mode is not allowed for container %v", [container.name])
        }
        
        violation[{"msg": msg, "details": {}}] {
            container := input.review.object.spec.initContainers[_]
            container.securityContext.privileged
            msg := sprintf("Privileged mode is not allowed for initContainer %v", [container.name])
        }